### ISSUE TITLE
circle-ci deploy to docker hub fails upon release

### ISSUE THREAD

**Issue by Remi-Gau** [bids-apps/base_validator#6]
@sappelhoff I may need your help to trouble shoot that one

**Comment by sappelhoff** [comment]
Unfortunately I cannot invite you to the ["bids" Dockerhub organization](https://hub.docker.com/u/bids) because we have been grandfathered on that account (already have 9 out of 3 possible team members). :thinking: 

But in any case this seems to be a username/password issue. I'll look around a bit.

![image](https://user-images.githubusercontent.com/9084751/210247369-dc5ff57e-bd8e-474f-9ab8-7756302ded52.png)

**Comment by sappelhoff** [comment]
okay I updated the credentials, it seems to work now.

https://hub.docker.com/repository/docker/bids/base_validator

Please close this if you are happy @Remi-Gau

**Comment by Remi-Gau** [comment]
Thanks. Do you know if the credentials are the same across all repos in the bids app orga?

**Comment by sappelhoff** [comment]
Not 100% sure, but I think it's always Chris G.

and as far as I know the members of the org have to use their Dockerhub credentials to push to the org -- I haven't seen org specific credentials that are not tied to an individual account

**Comment by Remi-Gau** [comment]
so circle-ci somehow knows who triggered the workflow to push to docker hub?
how about for automatically triggered workflow?

https://github.com/bids-apps/base_validator/blob/a93ef6ad63d020bd563a770d88c3e5354fadf00b/.circleci/config.yml#L38

**Comment by sappelhoff** [comment]
nope, I stored my personal credentials as secrets in the circleci settings, so from now on, all pushes will be as if I did them. It's not really ideal, but that was also the previous setup (just that it was Chris G's credentials, not mine)

**Comment by Remi-Gau** [comment]
ok got it. thanks
